import Head from "next/head";
import { RouterOutputs, api } from "@/utils/api";
import { SignInButton, useUser } from "@clerk/nextjs";
import dayjs from "dayjs"
import relativeTime from "dayjs/plugin/relativeTime"
import Image from "next/image";

dayjs.extend(relativeTime)

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;
  return (
    <div className="flex gap-3 w-full">
      <Image src={user.profileImageUrl} alt="Profile Image" className="rounded-full" width={56} height={56}/>
      <input type="text" placeholder="Type Some emojis!" className="bg-transparent grow outline-none" />
    </div>
  )
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number]

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return <div className="p-4 border-b border-slate-400 flex gap-3">
    <Image src={author.profileImageUrl} alt={`@${author.username} profile picture`} className="rounded-full" width={56} height={56}/>
    <div className="flex flex-col">
      <div className="flex text-slate-300 font-medium gap-1">
        <span>{`@${author.username}`}</span><span className="font-light">{`· ${dayjs(post.createdAt).fromNow()}`}</span>
      </div>
      <span>{post.content}</span>
    </div>
  </div>
}

export default function Home() {
  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>

  if (!data) return <div>Something went wrong </div>
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl border-x h-full border-slate-400">
          <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn && <div className="flex justify-center"><SignInButton /></div>}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data.map((post) => (
              <PostView post={post.post} author={post.author} key={post.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
